version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    # parameters:
    #   s3-bucket-name:
    #     type: string
    #     default: test-api-circleci
    #   stack-name:
    #     type: string
    #     default: testapistack
      
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - run:
          name: Install AWS SAM CLI
          command: |
            pip install aws-sam-cli
      - run:
          name: configure AWS credentials
          command: |
            ROLE_ARN="arn:aws:iam::Account_ID:role/dynamic-aws-credentials"
            SESSION_NAME="circleci-session"
            TEMP_CREDENTIALS=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name $SESSION_NAME)
            echo temp
            export AWS_ACCESS_KEY_ID=$(echo $TEMP_CREDENTIALS | jq -r '.Credentials.AccessKeyId')
            echo accesskey
            export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_CREDENTIALS | jq -r '.Credentials.SecretAccessKey')
            echo secretkey
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: verifying working directory
          command: |
            pwd
            ls -la
      - run:
          name: Deploy lambda function
          command: |
            zip function.zip Lambda.py
            pwd
            ls
            if aws lambda get-function --function-name lambda_handler; then
              aws lambda update-function-code --function-name lambda_handler --zip-file fileb://function.zip --region $AWS_DEFAULT_REGION
            else
              aws lambda create-function --function-name lambda_handler \
                --zip-file fileb://function.zip \
                --handler lambda_function.lambda_handler \
                --runtime python3.8 \
                --role arn:aws:iam::992382428282:role/lambdadeploytest \
                --region $AWS_DEFAULT_REGION
            fi   

workflows:
  version: 2
  testdeploy:
    jobs:
      - deploy:
          name: deploy-lambdafunction
          context: aws-credential-dev
          filters:
            branches:
              only: main
                                
              
